# Generated by Django 2.2.24 on 2021-08-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sample_9',
            field=models.IntegerField(blank=True, choices=[('B4', 'ブロンズ4'), ('B3', 'ブロンズ3'), ('B2', 'ブロンズ2'), ('B1', 'ブロンズ1'), ('S4', 'シルバー4'), ('S3', 'シルバー3'), ('S2', 'シルバー2'), ('S1', 'シルバー1'), ('G4', 'ゴールド4'), ('G3', 'ゴールド3'), ('G2', 'ゴールド2'), ('G1', 'ゴールド1'), ('P4', 'プラチナ4'), ('P3', 'プラチナ3'), ('P2', 'プラチナ2'), ('P1', 'プラチナ1'), ('D4', 'ダイア4'), ('D3', 'ダイア4'), ('D2', 'ダイア4'), ('D1', 'ダイア4'), ('MA', 'マスター'), ('PR', 'プレデター')], null=True, verbose_name='ランク(rank)'),
        ),
    ]
